# Wave 5

## Numpy Labs

In [1]:
import numpy as np

### abc_numpy

In [2]:
#Create a numpy array of strings containing letters 'a' through 'j' (inclusive) of the alphabet. 
#Then, use numpy array attributes to print the following information about this array:
#dtype of array, shape of array, size of array


# create numpy array of letters a-j
letter_array = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print("Letter Array: ", letter_array)

# get dtype of array
print('dtype of array:',letter_array.dtype)

# get shape of array
print('shape of array:', letter_array.shape)

# get size of array
print('size of array:', letter_array.size)

Letter Array:  ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']
dtype of array: <U1
shape of array: (10,)
size of array: 10


### create_ndarray

In [3]:
import numpy as np

# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 


X = np.full((4,4),(1,2,3,4))
print(X)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


### create_ndarray1

In [4]:
# Using the Built-in functions you learned about in the
# previous lesson, create a 4 x 4 ndarray that only
# contains consecutive even numbers from 2 to 32 (inclusive)

X =  np.arange(2, 33, 2).reshape(4, 4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


### pick_odd

In [5]:
# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
# Afterwards use Boolean indexing to pick out only the odd numbers in the array
num = np.arange(1,26).reshape(5,5)
# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = num[num % 2 == 0]

# Use Boolean indexing to pick out only the odd numbers in the array
Y = num[num % 2 != 0]

print(f'List of even numbers from 1 to 25:', X)

print(f'List of odd numbers from 1 to 25:', Y)

List of even numbers from 1 to 25: [ 2  4  6  8 10 12 14 16 18 20 22 24]
List of odd numbers from 1 to 25: [ 1  3  5  7  9 11 13 15 17 19 21 23 25]


## Pandas Labs 

In [6]:
import pandas as pd

### book_r

In [7]:
# Since we will be working with ratings, we will set the precision of our 
# dataframes to one decimal place.
pd.set_option('precision', 1)

# Create a Pandas DataFrame that contains the ratings some users have given to a
# series of books. The ratings given are in the range from 1 to 5, with 5 being
# the best score. The names of the books, the authors, and the ratings of each user
# are given below:

books = pd.Series(data = ['Great Expectations', 'Of Mice and Men', 'Romeo and Juliet', 'The Time Machine', 'Alice in Wonderland' ])
authors = pd.Series(data = ['Charles Dickens', 'John Steinbeck', 'William Shakespeare', ' H. G. Wells', 'Lewis Carroll' ])

user_1 = pd.Series(data = [3.2, np.nan ,2.5])
user_2 = pd.Series(data = [5., 1.3, 4.0, 3.8])
user_3 = pd.Series(data = [2.0, 2.3, np.nan, 4])
user_4 = pd.Series(data = [4, 3.5, 4, 5, 4.2])

# Users that have np.nan values means that the user has not yet rated that book.
# Use the data above to create a Pandas DataFrame that has the following column
# labels: 'Author', 'Book Title', 'User 1', 'User 2', 'User 3', 'User 4'. Let Pandas
# automatically assign numerical row indices to the DataFrame. 

# Create a dictionary with the data given above
dat = {'Author':authors,'Book Title':books,'User 1':user_1,'User 2':user_2,'User 3':user_3,'User 4':user_4}

# Use the dictionary to create a Pandas DataFrame
book_ratings = pd.DataFrame(dat)

# If you created the dictionary correctly you should have a Pandas DataFrame
# that has column labels: 'Author', 'Book Title', 'User 1', 'User 2', 'User 3',
# 'User 4' and row indices 0 through 4.
book_ratings

Author           Book Title  User 1  User 2  User 3  User 4
0      Charles Dickens   Great Expectations     3.2     5.0     2.0     4.0
1       John Steinbeck      Of Mice and Men     NaN     1.3     2.3     3.5
2  William Shakespeare     Romeo and Juliet     2.5     4.0     NaN     4.0
3          H. G. Wells     The Time Machine     NaN     3.8     4.0     5.0
4        Lewis Carroll  Alice in Wonderland     NaN     NaN     NaN     4.2

In [8]:
# Now replace all the NaN values in your DataFrame with the average rating in
# each column. Replace the NaN values in place. HINT: you can use the fillna()
# function with the keyword inplace = True, to do this. Write your code below:
book_ratings.fillna(book_ratings.mean(),inplace=True)

book_ratings

Author           Book Title  User 1  User 2  User 3  User 4
0      Charles Dickens   Great Expectations     3.2     5.0     2.0     4.0
1       John Steinbeck      Of Mice and Men     2.9     1.3     2.3     3.5
2  William Shakespeare     Romeo and Juliet     2.5     4.0     2.8     4.0
3          H. G. Wells     The Time Machine     2.9     3.8     4.0     5.0
4        Lewis Carroll  Alice in Wonderland     2.9     3.5     2.8     4.2

### sun_planets

In [9]:
# Create a Pandas Series that contains the distance of some planets from the Sun.
# Use the name of the planets as the index to your Pandas Series, and the distance
# from the Sun as your data. The distance from the Sun is in units of 10^6 km

distance_from_sun = [149.6, 1433.5, 227.9, 108.2, 778.6]

planets = ['Earth','Saturn', 'Mars','Venus', 'Jupiter']

# Create a Pandas Series using the above data, with the name of the planets as
# the index and the distance from the Sun as your data.
dist_planets = pd.Series(distance_from_sun,index=planets)
print(dist_planets)

Earth       149.6
Saturn     1433.5
Mars        227.9
Venus       108.2
Jupiter     778.6
dtype: float64


In [10]:
# Calculate the number of minutes it takes sunlight to reach each planet. You can
# do this by dividing the distance from the Sun for each planet by the speed of light.
# Since in the data above the distance from the Sun is in units of 10^6 km, you can
# use a value for the speed of light of c = 18, since light travels 18 x 10^6 km/minute.
c = 18
time_light = (dist_planets)/c
print(time_light)

Earth       8.3
Saturn     79.6
Mars       12.7
Venus       6.0
Jupiter    43.3
dtype: float64


In [11]:
# Use Boolean indexing to select only those planets for which sunlight takes less
# than 40 minutes to reach them.
close_planets = time_light[time_light<40]
print(close_planets)

Earth     8.3
Mars     12.7
Venus     6.0
dtype: float64
